Homework1
made-ml-in-prod-2021/liliyamakhmutova pull request #2
Opened 2021-05-08 14:22 UTC by LiliyaMakhmutova

Что было сделано:
-2) Ветка была названа homework1 (1 балл)
-1) Код в папке ml_project
0) Описываю проделанную работу по каждому пункту (2 балла)
1) Выполнен EDA: описаны фичи и их значения, информация о датасете и некоторые общие статистики, построены графики для понимания корреляций/распределений, сравниваются результаты на различных моделях: LogisticRegression, LinearDiscriminantAnalysis, KNeighborsClassifier, DecisionTreeClassifier, GaussianNB, SVM (2 балла)

2) Проект имеет модульную структуру, разбит по папкам:
- configs (конфигурационные файлы, внутри папка model_config с конфигурациями моделей)
- data (в raw лежит датасет, а в predicted -- предсказания модели)
- logs (содержит файлы с логами)
- models (содержит сохраненные модели)
- notebooks (содержит jupyter-ноутбук с EDA)
- outputs (содержит папки и файлы, созданные hydra)
- src (содержит исходный код для обучения и предсказания: data - файлы для работы с датасетом, enities - для основных функций обработки данных, features - для обработки, извлечения и удаления столбцов данных, models - для работы с моделями: обучения, предсказание, оценка, сохранение)
- tests (содержит тесты для кода из src: отдельных модулей и всего пайплайна)
(2 балла)

3) использованы логгеры: используется логгер из библиотеки logging, его конфигурация содержится в файле configs/logging_config.yaml, логи хранятся в папке logs  
(2 балла)

4) написаны тесты на отдельные модули и на прогон всего пайплайна - в папке tests (3 балла)

5) Для тестов генерируются синтетические данные, приближенные к реальным. Была написана функция gen_synthetic_data (в tests/gen_synthetic_data.py), которая возвращает DataFrame аналогичный исходной выборке (внутри генерируются значения из нужного диапазона с помощью библиотеки random, то есть случайно, нестратифицированно).  
(3 балла)

6) Обучение модели конфигурируется с помощью конфигов в yaml, конфигурации в configs/model_config. Конкретно имеется две конфиругации: LogisticRegression и DecisionTreeClassifier (3 балла)

7) Используются датаклассы для сущностей из конфига, а не голые dict (см src/enities) (3 балла) 

8) Трансформер был слегка модифицирован (не знала, как можно написать лучше и по-другому, получалось примерно одно и то же), тесты, покрывающие различные случаи, имеются (? балла)

9) Описание обучения модели в readme имеется (3 балла)

10) Написана функция predict, которая принимает на вход артефакт/ы от обучения, тестовую выборку (без меток) и записывает предикт. Описание работы с функцией в readme имеется (3 балла)  

11) Используется hydra. Изначально использовала конфигурации из configs в .yaml (в том числе и логов), парсила dataclass, только потом решила, что все же попробую поработать с hydra, поэтому сделала это только в файле src/predict.py, так как dataclass все же нужен для п.7  (3 балла - доп баллы)

13) Самооценка: итого рассчитываю примерно на 30-34 балла, кажется, что почти все пункты соблюдены, в случае неправильной реализации буду исправлять после проверки (1 балл доп баллы)

2021-05-11 10:13 UTC, reconrus approved these changes
К сожалению, пока взвешенные комментарии могу оставить только по поводу стиля. Сам не до конца разобрался, как лучше организовывать логически. Поздно начал делать дз :(

Последний общий комментарий: думаю, стоит внести логи и бинари в `.gitignore` и удалить их из репозитория. То есть добавить 

~~~
*__pycache__/*
ml_project/logs/*
~~~

2021-05-11 10:13 UTC, reconrus commented on ml_project/requirements.txt
> +click
Я бы предложил воспользоваться `pip freeze`, чтобы зафиксировать конкретные версии используемых пакетов, на которых работоспособность кода была проверена.

2021-05-11 10:13 UTC, reconrus commented on ml_project/setup.py
> +        "hydra-core==1.0.6"
При написании комментария к `requirements.txt` ещё не видел данного перечня. Возможно, тогда имеет смысл удалить requirements.txt из репозитория.

2021-05-11 10:13 UTC, reconrus commented on ml_project/src/enities/model_params.py
> +    with open(f'{path}/../model_configs/logistic_regression.yaml', "r") as input_stream:
Думаю, имеет смысл выбрать один из вариантов кавычек и использовать его во всём проекте.

2021-05-11 10:13 UTC, reconrus commented on ml_project/src/enities/model_params.py
> +import yaml
В соответствии с PEP-8 порядок импортов должен быть следующий:

> Imports should be grouped in the following order:
    * Standard library imports.
    * Related third party imports.
    * Local application/library specific imports.

То есть в данном случае 

```
from dataclasses import dataclass, field

import yaml
from marshmallow_dataclass import class_schema
```

[Source](https://www.python.org/dev/peps/pep-0008/#imports)

2021-05-11 10:13 UTC, reconrus commented on ml_project/src/enities/feature_params.py
> +@dataclass()
Не очень, если честно, знаю, что будет, если попытаться вызвать декоратор. Но никогда не видел, чтобы так делали. Достаточно просто `@dataclass`. Буду очень рад, если поделитесь своим мнением по этому поводу!

2021-05-11 10:13 UTC, reconrus commented on ml_project/src/enities/train_pipeline_params.py
> +
Лишняя пустая строка

2021-05-11 10:13 UTC, reconrus commented on ml_project/src/models/__init__.py
> +)
В некоторых случаях Вы используете разделение бэкслешем, как, например, в `features/__init__.py`, а здесь при помощи скобочек. Я бы постарался остановиться на каком-нибудь одном варианте.
```
from .build_features import make_features, extract_target, \
    build_transformer, drop_columns
```

В PEP-8 прописано, что вариант со скобками более предпочтителен.

> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

[Source](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)

2021-05-11 10:13 UTC, reconrus commented on ml_project/src/predict.py
> +)
Аналогичный комментарий про порядок импортов

2021-05-22 17:45 UTC, Sergey-Pravdyukov commented
Логгирование выглядит слишком верзнеуровеным. Ведь смысл логгирования в том чтобы при возникновения бага быстро его локализовать. Сейчас мы можем лишь сказать на каком этапе поведение не такое как мы ожидаем.

2021-05-22 17:49 UTC, Sergey-Pravdyukov commented
`pytest tests/` ведет к отсутствию как пакета `pytest`, так и самих тестов.

2021-05-22 17:55 UTC, Sergey-Pravdyukov commented
И трансформер не нашел.

2021-05-22 17:59 UTC, Sergey-Pravdyukov commented
Выполняю `python src/train_pipeline.py configs/train_config.yaml` получаю такой [лог](https://pastebin.com/GdhSpPAt) ошибки.

2021-05-22 18:04 UTC, Sergey-Pravdyukov commented
Проверил пункты 1-9, дальше не стал проверять так как многие пункты не выполнены. Добавьте пожалуйста недостающий функционал и проверьте решение.

На данный момент пункты 4, 5, 8, 9 не выполнены, по 3 есть недочеты.

Если не желаете дорабатывать решение, то пожалуйста сообщите об этом. В таком случае я проверю ваше решение до конца и выставлю итоговую оценку.

2021-05-23 15:01 UTC, Sergey-Pravdyukov requested changes
Описал в комментариях каким пунктам стоит уделить внимание.

2021-05-30 09:28 UTC, LiliyaMakhmutova commented on ml_project/src/enities/feature_params.py
> +@dataclass()
Вячеслав, большое спасибо за замечания и ревью. Забыла совсем про PEP-8. @dataclass() или просто @dataclass эквивалентны, насколько я поняла (https://docs.python.org/3/library/dataclasses.html#module-level-decorators-classes-and-functions). Постараюсь все учесть.

2021-05-30 13:23 UTC, LiliyaMakhmutova commented
> 
> 
> Логгирование выглядит слишком верхнеуровеным. Ведь смысл логгирования в том чтобы при возникновения бага быстро его локализовать. Сейчас мы можем лишь сказать на каком этапе поведение не такое как мы ожидаем.

Здравствуйте, Сергей. Подскажите, пожалуйста, как это можно исправить?

2021-05-30 13:24 UTC, LiliyaMakhmutova commented
> 
> 
> `pytest tests/` ведет к отсутствию как пакета `pytest`, так и самих тестов.

Случайно исключила эту папку, сейчас добавила

2021-05-30 13:25 UTC, LiliyaMakhmutova commented
> 
> 
> И трансформер не нашел.

Он в папке src/features, если я все верно поняла

2021-05-30 13:25 UTC, LiliyaMakhmutova commented
> 
> 
> Проверил пункты 1-9, дальше не стал проверять так как многие пункты не выполнены. Добавьте пожалуйста недостающий функционал и проверьте решение.
> 
> На данный момент пункты 4, 5, 8, 9 не выполнены, по 3 есть недочеты.
> 
> Если не желаете дорабатывать решение, то пожалуйста сообщите об этом. В таком случае я проверю ваше решение до конца и выставлю итоговую оценку.

Постаралась все исправить. Прошу прощения, что так долго (в университете были экзамены).

2021-05-31 19:19 UTC, Sergey-Pravdyukov commented
Желаю вам продуктивного времени, ведь впереди еще много интересных и сложных работ по курсу!

Жду исправлений.

2021-05-31 19:21 UTC, Sergey-Pravdyukov requested changes
Желаю вам продуктивного времени, ведь впереди еще много интересных и сложных работ по курсу!

Жду исправлений.

2021-06-01 08:44 UTC, LiliyaMakhmutova commented
> 
> 
> Желаю вам продуктивного времени, ведь впереди еще много интересных и сложных работ по курсу!
> 
> Жду исправлений.

Спасибо большое, Сергей.
Я исправила все замечания, только не поняла, как с логами быть (как именно поменять логгирование). Вроде все работает теперь. И с трансформером возник вопрос тоже: у меня он есть в коде (без дампа в *.pkl, дамп я делала в другом проекте -- homework2 -- https://github.com/made-ml-in-prod-2021/liliyamakhmutova/tree/homework2/online_inference/models), Вы имели в виду сохранение трансформера в .pkl?

2021-06-25 09:28 UTC, Sergey-Pravdyukov approved these changes
32 балла.

2021-06-27 12:33 UTC, merged