Homework2
made-ml-in-prod-2021/liliyamakhmutova pull request #3
Opened 2021-05-15 20:15 UTC by LiliyaMakhmutova

Самооценка: 
1. inference модели был обернут в REST сервис (FastAPI), реализован endpoint-get /predict (3 балла)
2. Написан тест для /predict (в tests/api/test_app.py) (3 балла) 
3. Написан скрипт, который делает запросы к сервису (в api/make_request.py) (2 балла)
4. Сделана валидация: 
- если данных слишком много (20+ строк) - ошибка 413
- если неправильные features (включая не тот порядок) - ошибка 400
- не хватает данных (не 13 столбцов) - ошибка 400
(3 доп балла)
5. Написан Dockerfile и прилагается инструкция в readme (4 балл)
6. Оптимизирован размер docker image в соотвествие с best practices, не знаю, насколько все на 100% учла, описано в readme (3 доп балла)
7. Образ опубликован liliyamakhmutova/online_inference:1.0.0 (2 балла)
8. В readme описаны корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл)
9. Самооценка проведена (1 доп балл). Итого рассчитываю на 20-22 балла.

2021-05-22 17:31 UTC, Mikhail-M requested changes
удалите все .pyc

2021-05-30 08:42 UTC, LiliyaMakhmutova commented
> 
> 
> удалите все .pyc

сделано

2021-05-31 07:43 UTC, Mikhail-M commented on online_inference/api/app.py
> +abspath = os.path.abspath(__file__)
плохо , что такое есть

2021-05-31 07:44 UTC, Mikhail-M approved these changes
Оптимизация: 0 
валидация: 1
Тесты: 2 -- хорошо бы, чтобы модель мокалась в этих тестах или в фикстуре готовилась

Баллы: 16

2021-06-27 12:33 UTC, merged